version: '3'

services:
  database:
    image: mongo:latest
    container_name: mongodb-sharenergy
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=123456
    ports:
      - "27017:27017"

    
