version: '3'

services:
  database:
    image: mongo:latest
    container_name: database-sharenergy
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=123456
    ports:
      - "27017:27017"
    volumes:
      - ./mongorestore.sh:/docker-entrypoint-initdb.d/mongorestore.sh
      - ./db-dump:/db-dump
    
  backend:
    build: ./backend
    image: backend-sharenergy
    restart: always
    ports:
      - "5050:5050"
    environment:
      - MONGO_URI=mongodb://root:123456@database:27017/sharenergy-db?authSource=admin
    depends_on:
      - database

  frontend:
    build: ./frontend
    image: frontend-sharenergy
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - backend
